
let view = JSON.parse(localStorage.getItem("view"));
console.log(view);
let rating = view["rating"];
let title = view["title"];
let price = view["price"];
let image = view["image"];
let description = view["description"];

let myImg = document.getElementById("myImg");
let img = document.createElement("img");
img.setAttribute("src", image);
img.setAttribute("class", "img-fluid z-depth-1  mt-4");
myImg.appendChild(img);
let prodDetails = document.getElementById("prodDetails");
let label1 = document.createElement("label");
let label2 = document.createElement("label");
let label3 = document.createElement("label");
let label4 = document.createElement("label");
label1.innerHTML = `<strong> Title </strong>`;
label2.innerHTML = `<strong> Rating </strong>`;
label3.innerHTML = `<strong> Price </strong>`;
label4.innerHTML = `<strong> Description </strong>`;
let h5 = document.createElement("h5");
h5.innerText = title;
let p1 = document.createElement("p");
p1.innerText = rating;
let p2 = document.createElement("p");
let p3 = document.createElement("p");
p3.setAttribute("class", "pt-1");
let span = document.createElement("span");
span.setAttribute("class", "mr-1");
let strong = document.createElement("strong");
strong.innerText = price;
span.appendChild(strong);
p2.appendChild(span);
p3.innerText = description;
prodDetails.appendChild(label1);
prodDetails.appendChild(h5);
prodDetails.appendChild(label2);
prodDetails.appendChild(p1);
prodDetails.appendChild(label3);
prodDetails.appendChild(p2);
prodDetails.appendChild(label4);
prodDetails.appendChild(p3);
